# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: tinkoff-api-securities Node.js

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: ['14', '15', '16']
        name: Node ${{ matrix.node }} sample
        steps:
            - uses: actions/checkout@v2
            - name: Setup node
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node }}
            - run: npm install
            - run: npm build
            - run: npm test
              env:
                  SANDBOX_TOKEN: ${{ secrets.SANDBOX_TOKEN }}
